spring:
  telegram:
    bot:
      username: online_outletbot
      token: token

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/restful_api
    username: postgres
    password: Jahongir2002

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

  main:
    allow-circular-references: true

  jwt:
    secret:
      key: learning_center_secret_key
    expire:
      date:
        minute: 720

  mail:
    host: smtp.gmail.com
    port: 587
    username: dadayevjahongir82@gmail.com
    password: password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  otp:
    base-url: https://mpy3e9.api.infobip.com
    api-key: token
    sender: infoSMS

  person:
    profile:
      default-picture: AgACAgIAAxkBAAOtY169-FET4AHFRDzeDPYisIbRYNgAAu7CMRuuC_lKDlv-9xzmWdkBAAMCAANzAAMqBA
